spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  profiles:
    include: jwt, develop, prod, aws, credentials
    active: ${profile}


file:
  dir: /Users/johnn/Desktop/img/

slack:
  token: xoxb-2809610311684-4062997317088-XLAdHIH0Ayo33pZ4ivKVOiWP
  channel:
    monitor: '#3-개발-홈'